WorldThingGround event
coelckers/gzdoom pull request #1178
Opened 2020-09-06 12:35 UTC by nashmuhandes

Added WorldThingGround event to hook into the actor at exact moment its corpse spawns gibs upon being crushed.

[WorldThingGroundDemo.zip](https://github.com/coelckers/gzdoom/files/5179638/WorldThingGroundDemo.zip)

2020-09-11 08:22 UTC, Doom2fan commented
> Maybe its better to call it World Thing Grinded/Crushed?! Because Ground does not match other event names, World (Thing) Loaded/Revived/Destroyed/Damaged/etc, not World (Thing) Load/Revive/Destroy/Damage/etc.

"Ground" *is* the correct and matching name for it. [It's the simple present and present participle form of "Grind"](https://en.wiktionary.org/wiki/ground#Etymology_2), just like the other ones.

2020-09-11 19:00 UTC, MatthewTheGlutton commented
I'd like "Crushed" better because I thought at first this was about an actor hitting the ground.

2020-09-11 19:16 UTC, nashmuhandes commented
The naming [was already discussed about](https://github.com/coelckers/gzdoom/pull/1177#issuecomment-687757620) and will not be changed.

As for why not "crushed", because crushing, as far as the engine is concerned, is the situation where a thing is actively being crushed, and is not the intended target usage of this.

(Not to mention hooking up an event to thing crushing will probably be very, very, very slow!)

2020-09-11 19:25 UTC, MajorCooke commented
Technically speaking WorldThingDamage is already being called when an actor takes damage by any means.

2020-09-11 21:03 UTC, MekBoss commented
> 
> "Ground" _is_ the correct and matching name for it. [It's the simple past and past participle form of "Grind"](https://en.wiktionary.org/wiki/ground#Etymology_2), just like the other ones.

English is not the first (obviously) not the second and not even a third language that I know. For me it still sequences of specific symbols that mean X, or Y, or Z but also I, as a slang or in context specific situations.
So simple ground here is....eeeeee...what ground?
Ground specific event?
Ground-iose event?
Ground zero?
Ground control? Bowie David died four years ago, why such a sudden reference to one of his song?
???????????????????????????????????????????????????????

A little bit confusing name for the "after actor was crushed" event.

2020-09-11 21:36 UTC, MajorCooke commented
@MekBoss Grounding occurs after crushing. Because actors are crushed **into the ground.**

Now please drop it. Nash has made it clear that he's not going to change it, and that's final.

2020-09-27 11:45 UTC, coelckers requested changes
I see one issue here - there's two ways an actor can be ground to gibs - either by sprite replacement or going to a custom state, but the event gives no clue about this. Maybe it should so that processors can deal with both cases properly.

2020-09-27 14:07 UTC, nashmuhandes commented
> I see one issue here - there's two ways an actor can be ground to gibs - either by sprite replacement or going to a custom state, but the event gives no clue about this. Maybe it should so that processors can deal with both cases properly.

Acknowledged. Will work on this this week.

2020-09-30 01:58 UTC, nashmuhandes commented
Added the ability to get the crushed state, and here's a new demo to show its usage

[WorldThingGroundDemo2.zip](https://github.com/coelckers/gzdoom/files/5302753/WorldThingGroundDemo2.zip)

2020-10-25 19:10 UTC, merged