[WIP] PSprite Scale/Rotation/Pivot
coelckers/gzdoom pull request #1196
Opened 2020-09-30 15:13 UTC by MajorCooke

I'll add more details when its ready.

2020-10-01 05:10 UTC, coelckers requested changes
There's too much converting back and forth between doubles and floats. Please stay within double precision unless the result never needs to be converted back

2020-10-01 05:12 UTC, MajorCooke commented
The result never needs to be changed back at this point so I swapped it to floats.

2020-10-01 15:56 UTC, MajorCooke commented
`verts.first[0].Set(xx1, yy1, 0, u1, v1);` takes floats, not doubles. Ultimately, at the point of GetWeaponRect, that's when its finalized and doesn't need to be converted back to doubles, and I only set it up to convert from doubles to floats at any rate. Furthermore the added code like `x1/y1/x2/y2` as seen inside the `GetWeaponRect` is already set to floats so converting it all down to floats is what I went for.

2020-10-05 15:53 UTC, MajorCooke commented
I think I'm done. My last attempt to add parent pointers ended in complete failure and I have nothing more to add here. I'd rather do it in another PR so if it doesn't work out, it won't jeopardize my current work.

2020-10-25 14:58 UTC, coelckers commented
Merged manually

2020-10-25 14:58 UTC, closed without merging