Fixed config file being overriden when it's blocked by another application.
coelckers/gzdoom pull request #1236
Opened 2020-11-17 20:13 UTC by drfrag666

2020-11-17 20:29 UTC, alexey-lysiuk requested changes

2020-11-17 20:29 UTC, alexey-lysiuk commented on src/common/utility/configfile.cpp
> +		FileExisted = false;
This should be changed to `FileExisted = FileExists(PathName);`

2020-11-17 20:29 UTC, alexey-lysiuk commented on src/common/utility/configfile.cpp
> +		else I_Error ("Could not Open Config file.\n");
Could you please put `if` condition and statement on different lines? The same for `else` keyword and its statement.
Character case of the first letters in the error message is a bit random as well.

2020-11-17 20:29 UTC, alexey-lysiuk commented on src/common/utility/configfile.cpp
> +#include "filesystem.h"
Is it for `FileExists()` function? If so, this function is defined in `cmdlib.h` file.

2020-11-17 23:25 UTC, drfrag666 commented
Done.

2020-11-18 08:22 UTC, alexey-lysiuk commented
All speculations about this issue revolve around inability to read existing config file at some point for an unknown reason.
Did you test this change in the given case?

When I removed all permissions from config file, `FileExists()` returns `false` because `_wstat64()` returns zero.
So, the added code doesn't handle the advertised error condition, at least on Windows.

2020-11-18 10:17 UTC, drfrag666 commented
No but _stat is valid in order to check for file existence in theory. In case it returns -1 it's becouse the file doesn't exist or a parameter is not valid. I wouldn't be surprised if it's another bug in _stat. I could try to force the internal version in LZDoom, i'm using VS 2017 BTW. On the other side ::exits internally uses GetFileAttributesW.

2020-11-18 11:09 UTC, drfrag666 commented
The problem is real, what happens when you remove the permissions from the file? I assume the config is still overriden, i will do some testing in that situation then to see if it's a bug in _stat or ::exists work.

2020-11-18 11:34 UTC, drfrag666 commented
Well, i've just confirmed that _stat is broken on windows and the internal version works. I see it's still in GZDoom guarded by #ifdef _USING_V110_SDK71_ and it's _wstat64i32 but now _wstat64 is used instead.

2021-03-27 13:17 UTC, closed without merging