Added APROP_SoundClass
coelckers/gzdoom pull request #1333
Opened 2021-03-09 17:29 UTC by ShinyMetagross

- Added APROP_SoundClass to GetActorProperty, SetActorProperty, CheckActorProperty

2021-03-09 18:12 UTC, coelckers requested changes
Line 1623 needs to be changed to use proper 'if' syntax. It is completely unclear to me if this is even correct.
Line 1641 in S_FindSkinnedSound accesses 'player' without a null check. I also cannot see where the new member variable gets initialized. If you move over to this you must ensure that its default is always valid

2021-03-09 18:47 UTC, ShinyMetagross commented
Submitted the requested modifications.

2021-03-10 13:44 UTC, coelckers commented
There's still one thing I do not understand: Why was S_FindSkinnedSound changed to use the variable directly instead of calling GetSoundClass. Is it always guaranteed to be set elsewhere?

2021-03-10 18:24 UTC, ShinyMetagross commented
Yeah, you're right. Skipping GetSoundClass would also skip the skin code. That said, I've made another commit to remedy the situation.

2021-04-16 11:58 UTC, alexey-lysiuk requested changes

2021-04-16 11:58 UTC, alexey-lysiuk commented on src/playsim/d_player.h
> +	FString		SoundClass = "";
This initialization is useless, and `FString SoundClass;` generates less code.

2021-04-16 11:58 UTC, alexey-lysiuk commented on src/playsim/p_acs.cpp
> +			if (actor->player != NULL)
We prefer `nullptr` over `NULL`.

2021-04-16 11:58 UTC, alexey-lysiuk commented on src/playsim/p_acs.cpp
> +				}
This code block is useless as the next line do assignment unconditionally.

2021-04-16 11:58 UTC, alexey-lysiuk commented on src/playsim/p_user.cpp
> +		("SoundClass", SoundClass);
All key names are in lower case.

2021-04-16 11:58 UTC, alexey-lysiuk commented on src/sound/s_advsound.cpp
> +
Could you please avoid addition of empty lines?

2021-04-16 11:58 UTC, alexey-lysiuk commented on src/sound/s_sound.h
> +const char *GetSoundClass(AActor *pp);
I would rather move this function to `AActor` class instead of making it "public".
Otherwise, it should be prefixed with `S_` at least.

2021-05-05 16:38 UTC, ShinyMetagross commented
Please re-review whenever possible.

2021-05-28 18:22 UTC, merged