Use RDTSC on Linux if possible for stats
coelckers/gzdoom pull request #1567
Opened 2022-03-08 17:03 UTC by OrdinaryMagician

After some research I figured how to implement this. So far, all seems good, but it should get some testing.

Puts the final nail in the coffin for issue #1479, as it will avoid clock_gettime whenever possible.

2022-03-08 17:17 UTC, coelckers requested changes
Please make this C++17 compatible. Named struct initializers are a C++20 feature.
On GCC 7 this does not compile

2022-03-08 18:27 UTC, OrdinaryMagician commented
Should be done now. If there's a neater way of doing this I don't know it, I'm not well-versed in C++.

2022-03-08 20:15 UTC, wmerfalen commented
Greetings. The code looks good, but I do have some reservations about it's effectiveness on modern multi-core CPU's. The wikipedia article on the `rdtsc` instruction is rather disconcerting. It seemed at one point that the instruction worked on single core CPU's, but the results of it on multicore processors is now a big question mark. I'm hoping this message can serve as a catalyst for discussion on the topic. Cheers.

2022-03-08 21:36 UTC, OrdinaryMagician commented
With SMP there are quirks to it, and in some cases certain flaky CPUs or even flaky motherboards can cause jitter and whatnot, making the TSC unreliable. Obviously that matters a lot for the OS itself, where a reliable timer is essential. But for this case, where it's just used for some benchmarking stats, it's better to forcibly use it directly and let some inaccuracy slide rather than potentially having the OS offer a much more expensive clock source, which is what the linked issue is describing.

By its nature, HPET isn't exactly a good thing to access several hundred times per tick all over different parts of the code. It all piles up into loads and loads of extra latency that can for example drop a 60 FPS scene down to 5 FPS.

2022-03-08 21:43 UTC, madame-rachelle commented on src/common/engine/stats.h
> +#else // i386
Please use `#elif defined __i386__` here with a `#else return 0;` fall-through.

2022-03-08 22:08 UTC, OrdinaryMagician commented
Why do I have to change that? I copied the code verbatim from the windows version.

2022-03-08 22:14 UTC, madame-rachelle commented
Oh. It probably should be changed in the Windows version too, then. But that's beyond the scope of this PR.

The idea is to leave no assumptions about anything. If the processor is incompatible with the existing definitions, it should still successfully compile. It's not so much *this* instance that it is important for - it's just generally more of a good habit to have.

2022-03-08 22:50 UTC, OrdinaryMagician commented
Ah, I'll copy over the changes you made, then.

2022-03-09 22:15 UTC, madame-rachelle approved these changes

2022-03-15 22:12 UTC, merged